export const RATE_LIMITS = {
    AUTH_WINDOW_MS: 15 * 60 * 1000,
    AUTH_MAX_ATTEMPTS: 10,
    REFRESH_WINDOW_MS: 15 * 60 * 1000,
    REFRESH_MAX_ATTEMPTS: 30,
    COMPLAINT_SUBMIT_WINDOW_MS: 15 * 60 * 1000,
    COMPLAINT_SUBMIT_MAX: 10,
    OBSERVATION_WINDOW_MS: 15 * 60 * 1000,
    OBSERVATION_MAX: 20,
};
export const UPLOAD_LIMITS = {
    MAX_IMAGE_SIZE_BYTES: 8 * 1024 * 1024,
    ALLOWED_MIME_TYPES: ['image/jpeg', 'image/png', 'image/webp'],
};
export const DUPLICATE_DETECTION = {
    PROXIMITY_RADIUS_METRES: 50,
    MAX_CANDIDATES_CHECKED: 3,
};
export const CASCADE_RISK = {
    RADIUS_METRES: 200,
    TRIGGER_CATEGORIES: ['Water Leakage', 'Sewage'],
    TARGET_CATEGORIES: ['Road Damage', 'Pothole', 'Drainage'],
};
export const FIELDMESH = {
    AUTO_ELEVATE_CONFIDENCE_THRESHOLD: 0.8,
    LOW_CONFIDENCE_FLAG_THRESHOLD: 0.4,
    POINTS_OBSERVATION_SUBMITTED: 2,
    POINTS_OBSERVATION_ELEVATED: 15,
    POINTS_TASK_COMPLETED: 10,
};
export const REPUTATION = {
    POINTS_COMPLAINT_SUBMITTED: 5,
    POINTS_UPVOTE_RECEIVED: 2,
};
export const PULSE_GRID = {
    WINDOW_HOURS: 48,
    RECOMPUTE_CRON: '0 * * * *',
};
export const SILENT_SIGNAL = {
    WEATHER_SENSITIVE_CATEGORIES: ['Water Leakage', 'Drainage', 'Sewage', 'Road Damage', 'Pothole'],
    RAIN_EVENT_THRESHOLD_MM: 15,
    SEASONAL_SIGNIFICANCE_MULTIPLIER: 1.8,
    SEASONAL_WINDOW_DAYS: 7,
    FORECAST_VALIDITY_DAYS: 10,
    MIN_YEARS_FOR_PATTERN: 2,
    DAILY_CRON: '0 2 * * *',
};
export const WARD_HEALTH = {
    STATS_WINDOW_DAYS: 30,
    BACKLOG_PENALTY_PER_OPEN: 2,
    BACKLOG_PENALTY_CAP: 30,
    SLOW_RESOLUTION_THRESHOLD_HOURS: 72,
    SLOW_RESOLUTION_PENALTY: 15,
};
export const TOKEN_LIFETIMES = {
    ACCESS_TOKEN_EXPIRY: '15m',
    REFRESH_TOKEN_EXPIRY: '7d',
    REFRESH_TOKEN_COOKIE_MAX_AGE_MS: 7 * 24 * 60 * 60 * 1000,
};
export const PAGINATION = {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 10,
    MAX_LIMIT: 50,
};
